server.port=8080

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/booklibrary
spring.datasource.username=vijaysharma
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false